
FROM python:3.9

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем только файл зависимостей для кэширования
COPY requirements.txt /app/

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код в контейнер
COPY . /app/

# Устанавливаем переменную окружения PYTHONPATH
ENV PYTHONPATH=/app

# Открываем порт
EXPOSE 8000

# Запускаем приложение
CMD ["uvicorn", "app.main:app", "--reload"]
