# Используем Node.js образ
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app


COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все остальные файлы проекта в контейнер
COPY . .

# Строим проект
RUN npm run build

# Открываем порт для фронтенда
EXPOSE 3000

# Запускаем Nuxt
CMD ["npm", "run", "start"]
